function s1_adapt_figs
% script to check distance in population space from final learning trials

%% Set up meta info
    if ispc
        homefolder = 'C:\Users\Raeed';
    else
        homefolder = '/Users/raeed';
    end
    
    dataroot = fullfile(homefolder,'Library','CloudStorage','OneDrive-UniversityofPittsburgh','0-projects','s1-adapt','data','td-library');
    file_info = dir(fullfile(dataroot,'*CO*.mat'));
    filenames = horzcat({file_info.name})';

    % Load up data into cell array
    trial_data_cell = load_curl_data(fullfile(dataroot,filenames));

    % Load spindle simulated data
    sim_file_info = dir(fullfile(dataroot,'spindle_sim','*CO*.mat'));
    sim_filenames = horzcat({sim_file_info.name})';
    td_sim_cell = load_curl_data(fullfile(dataroot,'spindle_sim',sim_filenames));

%% Active mahalanobis figure
    active_params = struct(...
        'save_figures', false,...
        'figsavedir', fullfile(homefolder,'Wiki','0-projects','s1-adaptation','figures','mahal','active'),...
        'num_dims', 16,...
        'num_mahal_dims', 4,...
        'alignment_event', 'idx_movement_on',...
        'arrays_to_plot', {{'M1','S1'}},...
        'smoothing_window_size', 10 ...
    );
    
    mahal_curve_table = iterate_mahal_curves(trial_data_cell,active_params);

    % plot out all mahal curves, colored by array
    plot_mahal_summary(mahal_curve_table,active_params)

%% Passive mahalanobis figure
    passive_params = struct(...
        'save_figures', false,...
        'figsavedir', fullfile(homefolder,'Wiki','0-projects','s1-adaptation','figures','mahal','passive'),...
        'num_dims', 16,...
        'num_mahal_dims', 4,...
        'alignment_event', 'idx_bumpTime',...
        'arrays_to_plot', {{'M1','S1'}},...
        'smoothing_window_size', 10 ...
    );
    
    mahal_curve_table = iterate_mahal_curves(trial_data_cell,passive_params);
    plot_mahal_summary(mahal_curve_table,passive_params)

%% Simulated mahalanobis figure
    simulated_params = struct(...
        'save_figures', false,...
        'figsavedir', fullfile(homefolder,'Wiki','0-projects','s1-adaptation','figures','mahal','sim-active'),...
        'num_dims', 16,...
        'num_mahal_dims', 4,...
        'alignment_event', 'idx_movement_on',...
        'arrays_to_plot', {{'S1_musFor','S1_spindle'}},...
        'smoothing_window_size', 10 ...
    );

    mahal_curve_table = iterate_mahal_curves(td_sim_cell,simulated_params);
    plot_mahal_summary(mahal_curve_table,simulated_params)
    
end